--- !ruby/object:Jumpstart::Configuration
application_name: JM Counselling
business_name: JM Counselling
domain: example.com
support_email: support@example.com
default_from_email: Jumpstart <support@example.com>
business_address: ''
background_job_processor: async
email_provider: ''
personal_accounts: true
solargraph: false
register_with_account: false
apns: false
fcm: false
collect_billing_address: false
